package ru.sbt.mipt.oop;

public enum SensorEventType {
    LIGHT_ON, LIGHT_OFF, DOOR_OPEN, DOOR_CLOSED, ALARM_ACTIVATE, ALARM_DEACTIVATE,
    ALARM_CANCELING, ALARM_ON, CLOSE_FRONT_DOOR, LIGHT_ON_IN_HALL, ALL_LIGHTS_OFF, ALL_LIGHTS_ON
}
